### ISSUE TITLE
Container start fails, if image is not on host

### ISSUE THREAD

**Issue by unixlab** [openanalytics/containerproxy#18]
Hi all!

If you try to start a Container with the DockerEngine which is not present on the host system, the start of the container fails.
This was also noticed by an other user at the shinyproxy project:
https://github.com/openanalytics/shinyproxy/issues/82

I think it's ok ( try ) to pull the image everytime you start a new container.
If the image is up to date the container will start straight away.
If not it will be pulled no the host system and starts afterwards.

I added just one line of code to achieve that and will submit it as a pull request.
I'm neither a java expert nor have much experience with the container proxy project.
If you have any comments on this I'm happy to hear.
Otherwise I would love to see a release with this "feature".

Felix

**Comment by shrektan** [comment]
I oppose to this. At least it should not pull as long as the image already exists. Better behavior is have a command to build or pull, as it’s in docker-compose.

**Comment by unixlab** [comment]
Ok, thanks for the feedback and I agree on that.

What do you think about a new ( private ) function which checks if the image is present locally?
If not, the image can be pulled before starting the container.

I have updated the PR in a way I think this could be done.

**Comment by donarus** [comment]
We would also welcome this feature. +1 for it

**Comment by dramshaw-zymergen** [comment]
1 year later... maybe this can be merged and released? This is a simple yet rewarding feature that really eases complexity in managing shiny app distribution.

**Comment by dramshaw-zymergen** [comment]
> Sorry but I have to oppose to the PR. At least it should not pull as long as the image already exists.
> 
> IMO, better behavior is to check all the image exists. Even better to have a command to build or pull, as it’s in docker-compose.

IMO why would we not always want to execute the pull?  If the image hasn't changed then it would be a simple execution, if it _has_ changed (_latest_) we probably want the newer image.  What is the disadvantage of running the pull regardless of whether the image exists or not?

**Comment by shrektan** [comment]
Pull may fail and may take long time to perform. So long to timeout again and again and never work.

**Comment by LEDfan** [comment]
This has been fixed in [ShinyProxy 3.0.0](https://www.openanalytics.eu/blog/2023/03/02/shinyproxy-3.0.0/).
Note that you can specify a [pullPolicy](https://shinyproxy.io/documentation/configuration/#docker-image-pull-policy), to decide whether you want to always pull, if the image is not present or never.
