### ISSUE TITLE
Error during mvn install 

### ISSUE THREAD

**Issue by pavlalexandr** [openanalytics/containerproxy#20]
Hello, there are some problems with building the package:

During tests executions i faced the error:

> eu.openanalytics.containerproxy.ContainerProxyException: Failed to start container
>         at eu.openanalytics.containerproxy.test.proxy.TestProxyService.launchProxy(TestProxyService.java:61)
> Caused by: com.spotify.docker.client.exceptions.DockerRequestException:
> Request error: POST http://localhost:2375/containers/cfccf877155f36a9db74ceb66997f32c60d54dc228bde1c356c9313ca40136dc/start: 500, body: {"message":"driver failed programming external connectivity on endpoint
> hopeful_kare (31ad867b6789b97ffc0417ea1fd0b6615e697dd831e3f7c7f2a10432aba37816): Bind for 0.0.0.0:20000 failed: port is already allocated"}
> 
>         at eu.openanalytics.containerproxy.test.proxy.TestProxyService.launchProxy(TestProxyService.java:61)
> Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error

**Comment by LEDfan** [comment]
Hi

This is an error during the test phase of the build. We have some integration tests that require some external dependencies (e.g. Docker) but it also assumes some properties of the environment (i.e. in this case that port 20000 is not already allocated). If you just want to build a JAR, we advice to skip the tests (see the [readme](https://github.com/openanalytics/containerproxy#building-from-source).
If you would really like to run the tests, you should have a look at the GitHub Actions workflow we use: https://github.com/openanalytics/containerproxy/blob/master/.github/workflows/workflows.yaml This describes the dependencies needed to run the tests.

I'm closing this issue now, but feel free to open a new issue if you encounter any problem.
