### ISSUE TITLE
SAML Metadata visibility from SP side (shinyproxy)

### ISSUE THREAD

**Issue by mskyttner** [openanalytics/containerproxy#30]
For SAML authentication, the IdP wants to have a copy of the metadata from the SP side when adding the shinyproxy app. 

For the SAML metadata that gets generated in shinyproxy/containerproxy, is it possible to query the shinyproxy (service provider) side for this? It seems ...`/saml/SOO/**` and ...`/saml/login/**` are open but there seems to be [some probably intentional filtering](https://github.com/openanalytics/containerproxy/blob/master/src/main/java/eu/openanalytics/containerproxy/auth/impl/saml/SAMLConfiguration.java#L274-L279) going on so the "../saml/metadata" endpoint is not exposed (?). 

Or is there some (other) way to get hold of the generated metadata from shinyproxy using "curl" for example? If this is not already available (operator error :)), please consider adding documentation or functionality to expose the ...`/saml/metadata` for downloading (similar to what this link describes, I guess: https://docs.spring.io/spring-security-saml/docs/current/reference/html/configuration-metadata.html#configuration-metadata-sp-display). 

This could be useful (unless it is already possible) when troubleshooting the contradictory "200 OK error" page that a few of us shinproxy w SAML users are running into, see for example here: https://support.openanalytics.eu/t/saml-issue-status-code-200/1529. There is also a redirect loop that can occur sometimes that would also benefit from being able to download the IP metadata to double-check that it is correct.

**Comment by LEDfan** [comment]
Hi @mskyttner 

Thank you for opening this issue, exposing the SAML metadata is indeed required for lots of IDP software. This is implemented and will be available in the next release. We don't yet have an ETA for that release. If you really need it, the feature is already available at our develop branch (see https://github.com/openanalytics/containerproxy/commit/595f88d9f04b64053efd7c02a6aca0ca59da8086)

**Comment by LEDfan** [comment]
Hi @jat255 

We released ContainerProxy 0.8.8 and ShinyProxy 2.5.0 in which the SAML metadata is now exposed on the `/saml/metadata` path, e.g.: `localhost:8080/saml/metadata`.

Since this is fixed now, I'm closing this issue. As always, feel free to open a new issue if you encounter any problem.

**Comment by jat255** [comment]
I think this mention was for @mskyttner, but thanks for the heads-up anyway :)

**Comment by LEDfan** [comment]
Sorry, that was a copy-paste mistake...
