### ISSUE TITLE
Version 0.8.4 missing

### ISSUE THREAD

**Issue by johan13** [openanalytics/containerproxy#38]
[ShinyProxy 2.3.1 uses ContainerProxy version 0.8.4](https://github.com/openanalytics/shinyproxy/blob/v2.3.1/pom.xml#L65), but I cannot find that tag in this repository. I also cannot find the method ContainerSpec.setLabels. I there a newer release that has not yet been published on GitHub?

**Edit**: I found setLabels in the develop branch.

**Comment by johan13** [comment]
Thank you!

**Comment by tverbeke** [comment]
Thank you for the reminder, @johan13 !

**Comment by nickmelis** [comment]
I'm sorry but I still cannot see the tag v0.8.4. Am I missing something?

**Comment by LEDfan** [comment]
I just pushed the v0.8.4 tag : https://github.com/openanalytics/containerproxy/releases/tag/v0.8.4
