### ISSUE TITLE
containerproxy.service.UserService.java.isAdmin doesn't handle string arrays

### ISSUE THREAD

**Issue by warnes** [openanalytics/containerproxy#8]
This code doesn't handle the case where getAdminGroups returns a string array (even with only a single element)  
https://github.com/openanalytics/containerproxy/blob/144c4207fb2fa0bbb5ca071748d45c5e288ba43f/src/main/java/eu/openanalytics/containerproxy/service/UserService.java#L106-L111
because `isMember` is defined as:
https://github.com/openanalytics/containerproxy/blob/144c4207fb2fa0bbb5ca071748d45c5e288ba43f/src/main/java/eu/openanalytics/containerproxy/service/UserService.java#L140

As a consequence `shinyproxy` fails to assign admin roles when the admin-groups is an array.

**Comment by tverbeke** [comment]
Thanks @warnes - will fix!

**Comment by fmichielssen** [comment]
Hi @warnes , thanks for bringing this up.
A fix has been committed in the develop branch: https://github.com/openanalytics/containerproxy/commit/0907b03735061393eca02699c44963d047807ba2

**Comment by tverbeke** [comment]
Released with ContainerProxy 0.7.0
