### ISSUE TITLE
No support for OIDC JWT signed with ECDSA key.

### ISSUE THREAD

**Issue by nickmelis** [openanalytics/containerproxy#82]
Trying to use ShinyProxy with our own OpenID/OAuth2 Authenticator, which uses ECDSA keys to sign the JWT.
With vanilla containerproxy we get this errror when logging in:

```
2023-10-18 15:34:42.764 ERROR 1 --- [  XNIO-1 task-1] e.o.c.a.i.OpenIDAuthenticationBackend    : org.springframework.security.oauth2.core.OAuth2AuthenticationException: [invalid_id_token] An error occurred while attempting to decode the Jwt: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
```

The problem seems to be solved by adding the following bean definition to `eu.openanalytics.containerproxy.security.WebSecurityConfig`: 

```
  @Bean
  @ConditionalOnExpression ("'${proxy.authentication}' == 'openid'")
  public JwtDecoderFactory<ClientRegistration> oidcIdTokenDecoderFactory() {
    OidcIdTokenDecoderFactory factory = new OidcIdTokenDecoderFactory();
    SignatureAlgorithm signatureAlgorithm = SignatureAlgorithm.from(
      environment.getProperty("proxy.openid.jwks-signature-algorithm", "RS256"));
    factory.setJwsAlgorithmResolver(clientRegistration -> signatureAlgorithm);
    return factory;
  }
```

where `jwks-signature-algorithm` in our case is set to `ES256` in the main `application.yml` file passed in to ShinyProxy.

Has anyone had the same problem before? Is there an easier way to solve it?

**Comment by LEDfan** [comment]
Hi, thanks for opening this issue.
I didn't found a better way to configure the algorithm. We will include the above code in the next release, so that it's possible to configure this.

**Comment by LEDfan** [comment]
Hi, this is now part of the ShinyProxy 3.1.0 we released today. See https://shinyproxy.io/documentation/configuration/#jwks-signature-algorithm .  Thanks again for your suggestion!
