### ISSUE TITLE
Stop Using a Deprecated Docker Client

### ISSUE THREAD

**Issue by RealTYPICAL** [openanalytics/containerproxy#83]
Currently the shiny proxy uses `com.spotify:docker-client:jar:8.16.0` which is considered deprecated as of writing https://github.com/spotify/docker-client

Would it be possible to use its canonical replacement found here: https://github.com/docker-java/docker-java

The reason is that the spotify:docker-client has many issues associated with it in regards to the socket hanging when trying to listen for the response. It looks like it's a common problem with older versions of the spotify docker lib.

https://github.com/fabric8io/docker-maven-plugin/issues/344
https://github.com/fabric8io/docker-maven-plugin/issues/981
https://github.com/fabric8io/docker-maven-plugin/issues/552
https://github.com/fabric8io/docker-maven-plugin/issues/862

Some explanations in older issues for other projects indicate that it's related to an interaction between the native socket library, the system, and how it's being used (the spotify docker lib). In TCP HTTP the connection will close/once it has reached the end even if you try to read too much, but the domain socket will not.

Thanks in advance.

**Comment by LEDfan** [comment]
Hi, this is now part of the ShinyProxy 3.1.0 we released today. Thank you for opening this issue.
